#! /bin/sh

xrdb ~/.Xresources &

bspc config top_padding        24
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       3
bspc config window_gap         16

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#AF865A"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# It looks like these options get overridden by Compton...
bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

# Set up displays
bspc monitor -d I II III IV V

# startup
# phicom2 -b &
# mpv --loop --wid=0 ~/Downloads/d.gif
# dunst &
# feh-blur -d &
# pgrep xflux || xflux -l 43.36 -g 1.26 &
# udiskie &
# pkill 2bspwm ; 2bspwm
# colorer -R

brightnessctl set 15 &
picom -b &
sxhkd &
~/.fehbg
~/.config/polybar/launch.sh &
$HOME/scripts/feh-blur -d &
nm-applet &

xrdb ~/.Xresources &